on:
   push:
        branches:
        - master

jobs:
     build:
            runs-on: ubuntu-latest

  steps:
  -name:'Testing Github Action'
  run: echo Eslam
  -uses:actions/checkout@v3
  -name:'Login to Docker hub'
  run:docker login --username 

